DROP TABLE IF EXISTS Filial;

CREATE TABLE IF NOT EXISTS Filial(
    id      VARCHAR(255) PRIMARY KEY,
    NOME    VARCHAR(255) NOT NULL,
    RUA    VARCHAR(255) NOT NULL,
    NUMERO   INT NOT NULL,
    CIDADE  VARCHAR(255) NOT NULL,
    ESTADO   VARCHAR(255) NOT NULL,
    QTDESTRELA VARCHAR(255) NOT NULL
);